* Presentación: introducción a las bbdd
** Primera parte: introducción a la problemática
  En la misma presentación se tienen notas donde se explica qué debo explicar
  en cada una de ellas.
  Lo que vamos aprendiendo en esta presentación:
  - Bases de datos :: qué son y qué abreviatura se usa.
  - Gestión de las BBDD :: necesidad de las mismas y gestión tradicional.
  - Problemas de la gestión tradicional :: se muestran algunos problemas al
       tiempo que se introducen algunos conceptos técnicos antes de entrar de
       lleno en ello:
    - Tabla :: conjunto más o menos ordenado de datos.
    - Campo :: cada uno de los atributos de un registro.
    - Registro :: cada una de las filas (entradas) de una tabla.
    - Clave primaria (PK) :: campo o atributo que sirve para identificar cada
	 uno de los registros.
** Kahoot!
   En la presentación se tiene una diapositiva donde pone "Kahoot!" que anuncia
   que vamos a hacer un Kahoot! para comprobar que los "pocos" conceptos vistos
   hasta ahora han quedado bien asentados.
* Presentación: bases de datos relacionales
** Primera parte: Modelo Relacional y Modelo ER
  En esta presentación introducimos el Modelo Relacional, que es el modelo 
  utilizado en las BBDD Relacionales.
  Tras introducir el Modelo Relacional pasamos a hablar del lenguaje de 
  diagrama para el diseño de las bases de datos.
** Segunda parte: ejercicios de diseño con Modelo ER
   Vamos a diseñar pequeñas bases de datos usando para ello el Modelo ER. Se 
   tiene un documento con los enunciados que hay que imprimir para dárselo al
   alumnado y que puedan hacerlo ahí durante las clases. Este documento está
   dentro de la carpeta ejercicios.
** Tercera parte: continuamos con la presentación
   Ahora pasamos al diseño lógico. Aprendemos a construir el modelo relacional
   a partir del diseño conceptual, modelo ER.
   Durante el aprendizaje haremos ejercicios que consisten en pasar nuestros
   modelos ER anteriores a modelo relacional. Está en la carpeta ejercicios,
   dentro de la carpeta 02.
** Cuarta parte: Kahoot!
   Hacemos un Kahoot! sobre todo para repasar conceptos y que vayan quedando
   más o menos claros.
* Instalar MariaDB
  Instalamos MariaDB y aprendemos a entrar al intérprete de mariadb (mysql).
* SQL
** Parte 1: ejercicio guiado con BD alumnos_bd
   En esta parte vamos a aprender (a través de un ejercicio guiado) a:
   - Entrar al intérprete de mysql con el usaurio root.
   - Crear una base de datos llamada alumnos_bd.
   - Crear un usuario y dar todos los privilegios sobre la BD recién creada.
   - Salir del intérprete.
   - Volver a entrar al intérprete con el usuario recién creado.
   - Entrar a la BD que creamos.
   - Crear la tabla país y luego la tabla alumno.
   - Insertar registros en la tabla país.
   - Insertar registros en la tabla alumno.
   - Hacer algunos select.
** Parte 2: práctica 1: sobre la BD anterior
   Antes de comenzar con la práctica borramos todos los registros 
   introducidos: delete pais primero y delete alumno después.
   Esta práctica la pueden hacer entre dos alumnos. Les enseñaré a conectarse
   remotamente a una BD. Es interesante porque hay que hacer muchos insert y 
   pueden dividirse los insert (uno hace 10 y otro otros 10).
   Mejor si les paso el enunciado impreso.
** Parte 3: ejercicio guiado con select
   Podemos usar la BD de la parte 2 (práctica) para practicar con los select.
** Parte 4: práctica 2: select BD hoteles
   TENGO QUE HACER LA BD DE HOTELES.
* Mysqladmin
  Instalamos mysqladmin y hacemos todo lo aprendido en la UI web.
